# Generated by Django 5.2.3 on 2025-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='seccion',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_entrada',
            field=models.CharField(choices=[('numerado', 'Asiento Numerado'), ('general', 'Entrada General')], default='numerado', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='es_destacado',
            field=models.BooleanField(default=False, help_text='Marcar para el carrusel principal.'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='es_promocionado',
            field=models.BooleanField(default=False, help_text='Marcar para la sección inferior.'),
        ),
    ]
